apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNDU2 # Mot de passe root encodé en base64
  MYSQL_USER: c3ByaW5ndXNlcg==  # Nom d'utilisateur encodé en base64
  MYSQL_PASSWORD: c3ByaW5ncGFzc3dvcmQ= # Mot de passe encodé en base64