---
- name: Déployer les applications Kubernetes avec Ansible
  hosts: k8s_nodes
  become: yes
  tasks:
    - name: Déployer le frontend
      command: kubectl apply -f /cloud-projet/k8s/frontend/frontend.yaml

    - name: Déployer le backend
      command: kubectl apply -f /cloud-projet/k8s/backend/backend.yaml

    - name: Déployer le mysql
      command: kubectl apply -f /cloud-projet/k8s/backend/mysql.yaml

    - name: Déployer le secrets
      command: kubectl apply -f /cloud-projet/k8s/backend/secrets.yaml

    - name: Déployer le configmap
      command: kubectl apply -f /cloud-projet/k8s/backend/configmap.yaml
