# setup.yml
- name: Setup DevOps Environment on all nodes
  hosts: all
  become: yes
  vars_files:
    - credentials.yml

  tasks:
    - name: Update & Upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - curl
          - wget
          - git
          - unzip
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        update_cache: yes
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
